### ISSUE TITLE
implement display of @rend="check"

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#201] opened 2023-01-08 00:05 UTC
we recently decided to allow this value of @rend in the schema. but it seems that the display is not yet implemented for the editions of inscriptions. see e.g. DHARMA_INSIDENKKanjuruhan.xml.

**Comment by ajaniak** [comment] 2023-01-16 12:20
The issue is than the code from Epidoc hasn't been made to allow such implementation. So a generic rule won't work, I will have to implement it manually to all elements.

**Comment by arlogriffiths** [comment] 2023-01-16 12:31
is it possible to obtain from the EpiDoc community that the common code is changed so as to allow you to do what needs to be done mor easily?

**Comment by ajaniak** [comment] 2023-01-16 13:21
Not for such a feature, the stylesheets epidoc are for final rendering in website. I will add manually the condition when necessary. I have just pushed the code for seg so that it can be rendered in DHARMA_INSIDENKKanjuruhan.xml. Since it is using css it can take some times to be displayed.

**Comment by arlogriffiths** [comment] 2024-10-21 07:12
I have the feeling that `<seg rend="check">` is not working. See e.g. https://dharmalekha.info/texts/INSIDENKSilamanikundala and its sources code.

**Comment by michaelnmmeyer** [comment] 2024-10-22 09:21
Fixed in https://github.com/michaelnmmeyer/dharma/commit/2a30111d14809f63630ff0a3b14c0351a0a05bd5.

**Closed by michaelnmmeyer** 2024-10-22 09:21 UTC
Labels: enhancement
