### ISSUE TITLE
Extend an abbreviated word

### ISSUE THREAD

**Issue by amandinebricout** [erc-dharma/project-documentation#182] opened 2022-06-14 07:07 UTC
@arlogriffiths @danbalogh @ajaniak @manufrancis 
Yesterday, I encountered a problem when I wanted to use the tags `<choice><abbr></abbrv><expan></expan></choice>`that I found in the EGD 7.3 concerning the abbreviations. When I encoded it, Oxygen have reported an error explaining "expan could contain ex". My text uses saṁ as an abbreviation of saṁbaddha.
I can get around the problem by using `<abbr>saṁ</abbr><supplied reason="omitted">baddha</supplied>`. 
I am not sure that this solution can also be applied to a case like śudi for śuddhe dine. With the solution outlined in the guide, the encoding would be `<choice><abbr>śudi</abbr><expan>śuddhe dine</expan></choice>`where it is clear that śudi is a short expression for a longer one. By encoding `<abbr>śu</abbr><supplied reason="omitted">ddhe</supplied><abbr>di</abbr><supplied reason="omitted">ne</supplied>`, is it clear enough for the reader that śudi is used as an abbreviation of a longer expression? What is your opinion?

**Comment by danbalogh** [comment] 2022-06-14 07:41
Dear Amandine, this is an unresolved issue. Please see the discussion in the comments in the EGD Google Doc next to the bit on abbreviations; see also #146 .

I would definitely NOT recommend using `<supplied>` with any value of reason for resolving abbreviations, since `<supplied>` is for marking up something that ought to be there in the text but is not, while the resolution of an abbreviation is no such thing. (Well, actually I could imagine stretching the sense of `@reason="subaudible"` to include this, but EpiDoc is already stretching the interpretation of that, and we have stretched it further, so let's not now make it more complicated on top.) So anyway, I suggest you do one of the following two things:
A, just add an XML comment next to your abbreviation that this spot will need to be revisited when we have a DHARMA stance on the encoding; or
B, stick to the "traditional" EpiDoc method (which I think we should retain for DHARMA, see the thread linked above) and encode `<expan><abbr>saṁ</abbr><ex>baddha<ex></expan>`

@arlogriffiths : please, as soon as your time permits, have a look at #146 and leave your comment there.

**Comment by amandinebricout** [comment] 2022-06-14 07:52
Dear Daniel,

Sorry I did not read the comments in the EGD before creating this question. 
In any case thanks for the answer and the reference to the issue #146. It's much clearer to me now. 
If it is possible to use the Epidoc method, I will. If not, I will add a comment as suggested but I could also explain the abbreviation in a note in the apparatus. 
Thanks again for your help.

**Comment by danbalogh** [comment] 2022-06-14 07:56
@amandinebricout , I've just checked and to my surprise the solution B I recommended above does not work, because the DHARMA schema at present forbids `<ex>` anywhere. We don't want Axelle to have to change the schema before we have a final stance on the preferred method, so please just stick to a comment for the time being.

**Comment by amandinebricout** [comment] 2022-06-14 09:16
@danbalogh, Noted, I'll stick to adding a simple comment for now.

**Comment by arlogriffiths** [comment] 2022-06-15 05:16
I have answered to #146.

**Comment by danbalogh** [comment] 2022-06-15 10:06
Thanks, I've now written it up for the EGD and added my "report" to #146. You may want to discuss display with Axelle. My suggestions are in the "report".

@amandinebricout : when Axelle has made the necessary changes to the schema, you can start using the encoding. I advise that you think carefully about resolving things like śudi into śuddhe dine; I've written a few words about that in the EGD revision.

**Comment by amandinebricout** [comment] 2022-06-16 07:44
Dear Daniel, I am very grateful for the invitation to reflect on how to solve śudi and thus encode it. Your paragraph on this subject in the EGD is very enlightening. Indeed several expansions of the expression are possible and I too had wondered about the case-ending. I perfectly understand that expanding this expression presents the problem of choosing between several synonymous resolutions. This choice would ultimately be quite arbitrary. But, the presence of an abbreviation means that this abbreviation was understood by the readers of the time and that it reflects a fixed expression. If we hesitate about the expansion of an abbreviation, it means that its resolution is no longer obvious today. 
Therefore, I do not necessarily agree entirely with the advice to leave "common" abbreviations with multiple resolutions unresolved on the pretext that they should be understood by an expert audience. For my part (but this is my own opinion), I believe that the text should be made as explicit as possible so that its meaning is accessible to all, including non-expert and non-epigraphic scholars. Without making the expansion of this kind of abbreviations compulsory, I think it would be good to find a way to make them explicit. In a case like śudi, couldn't we invite to make the expression explicit in a note in the apparatus? If this solution does not suit you and you prefer to keep the version where giving the "common" extensions of abbreviations is not encouraged, would it not be wise to compile a list of these expressions with their meaning which be made available on the website for example?

**Comment by danbalogh** [comment] 2022-06-16 09:51
Dear Amandine, I'm glad you have thought about the matter and the points you raise are worth reflecting on, so I'll do so. On the whole, I disagree very strongly, but that too is just a personal opinion.

This has got very long in the writing, so here is the TLDR. I am **for** resolving abbreviations of ambiguous meaning (with some reservations, which have not been expressed in the EGD), and only against resolving those of unambiguous meaning, especially when the exact form of the resolution (as distinct from its meaning) is uncertain. As I see it, resolving abbreviations of unambiguous meaning offers very little advantage and comes at a cost that is not worth that advantage, namely on the one hand increased complexity and on the other hand decreased objectivity.

And here is the long story.

First, note that for abbreviations with multiple possible resolutions, I only recommend not expanding them when those resolutions are synonymous. The suggestion in the EGD concerns A) common abbreviations with a single straightforward resolution (in which case resolving the abbreviation is needless); and especially B) common abbreviations with more than one possible resolution of the same ultimate meaning (in which case resolving the abbreviation is not only needless but also forces editorial interpretation on the text). When you say "If we hesitate about the expansion of an abbreviation, it means that its resolution is no longer obvious today", you imply that you ignore this important detail, though your sentence about "several synonymous resolutions" shows that you are aware of it.

Second, by "expert" I don't mean people with years of epigraphic experience: anyone who actually reads an edition (e.g. in Sanskrit) will hopefully be either qualified enough to know those abbreviations or, to have the common sense to look them up in a dictionary. (e.g. śudi is in Monier-Williams, you don't even need Sircar's IEG). (I'm changing "expert" to "qualified" in the EGD now.) For everyone else, there is the accompanying translation, which will clarify the meaning to anyone unaware of it, without forcing you as editor to take a stance on the exact Sanskrit phrase that abbreviation is supposed to represent.

This takes me to my third point, the importance of distinguishing the resolution of an abbreviation from its meaning. You say that an "abbreviation was understood by the readers of the time and that it reflects a fixed expression". I completely agree with the first part of this, but the second is an entirely separate claim and I do not think it is right. For instance, every English speaker today understands the abbreviation "e.g.", but many (probably most) are unaware of the phrase it originally abbreviates. That Latin phrase is irrelevant to the meaning (the abbreviation is itself lexicalised), and when you read out a text with this abbreviation in it, you'll probably say "ee gee", or possibly "for example". Without being really lexicalised, the acronym NA may stand for Not Applicable, Not Available or No Answer. The three are by and large synonymous and in many contexts you cannot know which phrase was intended, while still understanding the meaning of the acronym. In different contexts the same NA may stand for Narcotics Anonymous or Namibia (and many more things), in which case resolving it is warranted. Similar illustrations could be multiplied. I as an editor of inscriptions don't want to claim to know which (if any) of multiple synonymous resolutions the long dead composer had in mind, and by choosing any specific resolution I would inevitably do that.

Fourth and most important, I think the edition itself should contain as little interpretation as possible. This was also sort of my ultimate point in 2 and 3 above. It's of course OK to interpret things, and to present your interpretation to readers. But the place for that is not primarily in the text of the edition. To my mind, an epigraphic edition's primary purpose is to faithfully represent what A) is there, or B) was in my opinion there, or C) was in my opinion meant to have been there on the substrate. What with all the signs and brackets (or the XML tags), our texts already look complex enough. I would not want to complicate this further with the resolution of abbreviations, which could very easily be mistaken by the reader for emendations or restorations. Or, even worse, some readers might (on the unconscious presupposition that the editor is infallible) take it as canon, and yet others might (on the unconscious presupposition that the editor is more fallible and/or less intelligent than they are) criticise the choice of one particular resolution over a synonymous one. Resolving straightforward abbreviations such as śudi is in my opinion not worth all that; and to wind up, I repeat that I'm not talking here about ambiguous or obscure abbreviations (though I would personally prefer to discuss those in an apparatus note or the commentary, rather than resolve them in the edition).

As for the practical side, you are of course free to explain that śudi means śukla-divase (or whatever expansion you prefer) in an apparatus note or another part of your editions. But I certainly don't think project members should be invited to do so. As for your suggestion of compiling a list, I'm pretty sure the DHARMA epigraphic glossary, which is a key deliverable of the project, will include abbreviations. But before that is achieved, do you really think that compiling a list of common abbreviations and suggested or possible resolutions would be worth the effort invested? Sure, it would be nice. In an ideal world, our texts would also be fully lemmatised, with every word morphologically analysed and linked to an entry in a dictionary as well as to the exact spot on a high-quality facsimile of the original. We are working to bring that sort of thing closer to reality, but we must go one small step at a time and by my priorities, there are much more important and urgent steps to be taken than clarifying well-known abbreviations (those that can be looked up in the dictionary). It's OK for your priorities to be different, but actually I don't think they are very different from mine: I assume you too would rather on the one hand do some actual research on your texts, and on the other, do non-research work towards short-term goals that offer a better gain/cost ratio.

**Comment by amandinebricout** [comment] 2022-06-16 12:39
Dear Daniel, 
First of all, I would like to thank you for your long answer, which has given me a better understanding of your intentions and whose argumentation is particularly relevant. I will try to answer with a short message to avoid extending ourselves in fruitless exchanges. 
On reading it, I understand that our opinions do not differ that much and that the misunderstanding was mainly due to the use of the expression "expert audience". I have noted the change to "qualified audience" which is more acceptable to me but not totally satisfying. 
After reading your explanations, I would reformulate these sentence as followed in order to better delimitate what is a "common abbreviation":  
"common abbreviations whose meaning can be found in dictionaries and epigraphic glossaries, especially if multiple resolutions with the same ultimate meaning are possible, are better left unresolved" followed by the example of śudi.

In my view, this clarifies more explicitly what is meant by common abbreviations and makes it easier to know when to extend or not. By this reformulation, the number of resolutions and interventions in the text is limited by something recognised by every one : dictionaries and glossaries. And at the end of the project, if the DHARMA epigraphic glossary is indeed online, it will serve as a guide for the reader to understand some of these unresolved abbreviations.
This is of course just a proposal. 
As for the rest, you have convinced me and I have nothing to add. Thank you again for these explanations, which have removed doubts and questions.

**Comment by danbalogh** [comment] 2022-06-16 12:55
Thanks to you too for engaging with the topic and making me think about. I'm OK with changing the stuff about a qualified audience to the specific criterion of dictionaries. I've changed the wording of the EGD again. I further changed to "published reference works" instead of "dictionaries and epigraphic glossaries".
Please close this thread if that sounds OK to you, or suggest further changes if it isn't.

**Comment by amandinebricout** [comment] 2022-06-16 13:00
I'm glad you agree with the proposal and I'm really happy for this fruitful exchange of ideas. Everything sounds clear for me now and I close this thread.

**Closed** 2022-06-16 13:00 UTC
